# Generated by Django 4.1.7 on 2023-04-18 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application_users', '0003_parent_organization_users_user_picture'),
        ('parent_organization', '0003_delete_parent_organization_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Complains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_type', models.CharField(default='Harassment', max_length=30)),
                ('bully_name', models.CharField(default='Unknown', max_length=50)),
                ('bully_id', models.CharField(blank=True, max_length=30, null=True)),
                ('bully_picture', models.ImageField(blank=True, null=True, upload_to='bully_pictures/')),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('complain_description', models.TextField(max_length=100)),
                ('complain_status', models.CharField(default='Processing', max_length=30)),
                ('complain_decision', models.CharField(blank=True, max_length=500, null=True)),
                ('bully_guilty', models.BooleanField(blank=True, default=False, null=True)),
                ('complainee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_users.parent_organization_users')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent_organization.parent_organization')),
            ],
        ),
    ]
