# Generated by Django 4.1.7 on 2023-04-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_complains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_complains',
            name='complain_description',
            field=models.TextField(max_length=1000),
        ),
    ]
