# Generated by Django 4.1.7 on 2023-05-03 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_complains', '0002_alter_user_complains_complain_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_type', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Complain Types',
            },
        ),
        migrations.AlterModelOptions(
            name='user_complains',
            options={'verbose_name': 'User Complains'},
        ),
        migrations.AlterField(
            model_name='user_complains',
            name='complain_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_complains.complain_types'),
        ),
    ]
