# Generated by Django 4.1.7 on 2023-05-12 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_complains', '0003_complain_types_alter_user_complains_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complain_types',
            options={'verbose_name': 'Complain Type'},
        ),
        migrations.AlterModelOptions(
            name='user_complains',
            options={'verbose_name': 'User Complain'},
        ),
    ]
