# Generated by Django 4.1.7 on 2023-05-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_complains', '0005_user_complains_complain_validation_usercomplainproof'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustToTest',
            fields=[
                ('proofName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('proof', models.ImageField(blank=True, null=True, upload_to='testing/')),
                ('proof_to_text', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Testing Image to Text',
            },
        ),
    ]
