# Generated by Django 4.1.7 on 2023-04-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent_organization_users',
            name='is_proctor',
            field=models.BooleanField(default=False),
        ),
    ]
