# Generated by Django 4.1.7 on 2023-03-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent_organization', '0002_alter_organization_type_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parent_organization_users',
        ),
    ]
